-- BDSandbox schema (run on startup if spring.datasource.initialize=true)
CREATE TABLE IF NOT EXISTS WEB_PAGE (
    ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255),
    URL  VARCHAR(255),
    "DESC" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DRIVERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    YEAR_OF_BIRTH INT
);
