CREATE TABLE IF NOT EXISTS WEB_PAGE (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), URL VARCHAR(255), "DESC" VARCHAR(255));
CREATE TABLE IF NOT EXISTS DRIVERS (ID INT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), YEAR_OF_BIRTH INT);
CREATE TABLE IF NOT EXISTS CARS (ID INT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), MODEL VARCHAR(255), MANUFACTURING_YEAR INT);
CREATE TABLE IF NOT EXISTS DRIVER_CAR (ID INT AUTO_INCREMENT PRIMARY KEY, DRIVER_ID INT NOT NULL, CAR_ID INT NOT NULL, CONSTRAINT fk_driver_car_driver FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID), CONSTRAINT fk_driver_car_car FOREIGN KEY (CAR_ID) REFERENCES CARS(ID), CONSTRAINT uq_driver_car UNIQUE (DRIVER_ID, CAR_ID));
CREATE TABLE IF NOT EXISTS USERS (ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(255) NOT NULL UNIQUE, PASSWORD_HASH VARCHAR(255) NOT NULL, ROLE VARCHAR(50) NOT NULL, DRIVER_ID INT NULL, CONSTRAINT fk_user_driver FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(ID));
